version: 0.2
env:
  variables:
    PACKAGE_VERSION: dev-$(date +%Y%m%d%H%M%S)
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      # Install AWS CLI
      curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      unzip awscli-bundle.zip
      sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
  build:
    commands:
      # Set up AWS CodeArtifact credentials
      aws codeartifact login --tool maven --domain abdulgafffoor --domain-owner 262874500832 --repository Sample-JavaSpringboot-App
      mvn −version
  post_build:
    commands:
      # Publish JAR artifact to AWS CodeArtifact
      aws codeartifact push --repository Sample-JavaSpringboot-App --domain abdulgafffoor --format maven --namespace development --package sample-javaspringboot --version $PACKAGE_VERSION --artifact target/*.jar
